# Generated by Django 2.0.1 on 2018-01-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('allergies', models.CharField(max_length=1000)),
                ('past_medical_history', models.CharField(max_length=1000)),
                ('medication_history', models.CharField(max_length=1000)),
                ('doctor_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.Doctor')),
                ('med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medications.Medication')),
            ],
        ),
    ]
