# Generated by Django 2.0.1 on 2018-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_Contacted',
            field=models.BooleanField(default=False),
        ),
    ]
