# Generated by Django 2.0.1 on 2018-01-29 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_is_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
