# Generated by Django 2.0.1 on 2018-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
